"""One-time legacy CSV -> SQLite migration, with a validation gate.

Read-only on every source. Idempotent: INSERT OR REPLACE everywhere, and the
canonical column set is derived from the FBS Week-16 frames (verified: all
129 files share one 206-column schema; FCS columns are a subset once the
accumulated 'Unnamed: *' junk is dropped).

Sources (plan §4):
  FBS   : 2024 Season/Week 16/{Team}_2024week16.csv   (full 2007-2024 history)
  FCS   : 2024 Season/Week 9 FCS/*2024week9*          (latest complete FCS
          snapshot; filenames there lack the '.' in '.csv'), fallback FCS Data/
  bins  : Bin Data/Bin_Data.csv
  talent: Talent Data/talent_{2023,2024}.csv
  SP+   : SP+ Data/SP_2023.csv (week 0) + SP+ Data/2024/SP_2024week{N}.csv
  preds : 2024 Season/Predictions/Week */preds_2024w{N}[_{day}].csv
  results: 2024 Season/Results/results_2024w{N}.csv  (season aggregate skipped
           — it is derived and will be regenerated by `analyze`)
"""

from __future__ import annotations

import glob
import re
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from cfb_model.api.mapping import normalize_school
from cfb_model.config import Settings, get_settings
from cfb_model.data.store import BOOL_COLUMNS, Store

PREDS_RE = re.compile(r"preds_(\d{4})w(\d+)(?:_([A-Za-z0-9]+))?\.csv$")
RESULTS_RE = re.compile(r"results_(\d{4})w(\d+)\.csv$")


def _read_clean(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    return df[[c for c in df.columns if not c.startswith("Unnamed")]]


def _played_rows(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["School"].notna()].reset_index(drop=True)


def run_migration(settings: Settings | None = None, log=print) -> Store:
    settings = settings or get_settings()
    settings.ensure_dirs()
    store = Store(settings.db_path)

    # --- schema from the canonical FBS frame ---
    fbs_files = sorted(glob.glob(str(settings.legacy_season_dir / "Week 16" / "*_2024week16*.csv")))
    if not fbs_files:
        raise RuntimeError("No FBS Week 16 source files found")
    canonical_cols = list(_read_clean(fbs_files[0]).columns)
    store.init_schema(canonical_cols)
    log(f"Schema initialized with {len(canonical_cols)} team-frame columns")

    # --- FBS frames ---
    for path in fbs_files:
        df = _played_rows(_read_clean(path))
        key = normalize_school(df["School"].iloc[0])
        store.replace_team_frame(key, "fbs", df)
    log(f"FBS frames migrated: {len(fbs_files)}")

    # --- FCS frames: Week 9 snapshot, then FCS Data fallback ---
    fcs_files = sorted(glob.glob(str(settings.legacy_season_dir / "Week 9 FCS" / "*2024week9*")))
    fcs_keys: set[str] = set()
    for path in fcs_files:
        df = _played_rows(_read_clean(path))
        if df.empty:
            continue
        key = normalize_school(df["School"].iloc[0])
        store.replace_team_frame(key, "fcs", df)
        fcs_keys.add(key)
    log(f"FCS frames migrated from Week 9 snapshot: {len(fcs_keys)}")

    fallback = 0
    for path in sorted(glob.glob(str(settings.legacy_fcs_data / "*_data.csv"))):
        df = _played_rows(_read_clean(path))
        if df.empty:
            continue
        key = normalize_school(df["School"].iloc[0])
        if key in fcs_keys or key in store.team_keys("fbs"):
            continue
        store.replace_team_frame(key, "fcs", df)
        fcs_keys.add(key)
        fallback += 1
    log(f"FCS frames added from FCS Data fallback: {fallback}")

    # --- bins ---
    bins = pd.read_csv(settings.legacy_bin_csv)
    bins = bins[[c for c in bins.columns if not c.startswith("Unnamed")]]
    store.upsert_bins(bins)
    log(f"Bins migrated: {len(bins)} rows")

    # --- talent ---
    for path in sorted(glob.glob(str(settings.legacy_talent_dir / "talent_*.csv"))):
        season = int(re.search(r"talent_(\d{4})", path).group(1))
        talent = pd.read_csv(path)
        store.upsert_talent(season, talent[["School", "Talent"]].dropna(subset=["School"]))
        log(f"Talent {season}: {len(talent)} rows")

    # --- SP+ snapshots ---
    sp_2023 = settings.legacy_sp_dir / "SP_2023.csv"
    if sp_2023.exists():
        sp = pd.read_csv(sp_2023)
        store.upsert_sp(2023, 0, sp[["Team", "Rating"]].dropna(subset=["Team"]))
        log(f"SP+ 2023 (week 0): {len(sp)} rows")
    for path in sorted(glob.glob(str(settings.legacy_sp_dir / "2024" / "SP_2024week*.csv"))):
        week = int(re.search(r"week(\d+)", path).group(1))
        sp = _read_clean(path)
        store.upsert_sp(2024, week, sp[["Team", "Rating"]].dropna(subset=["Team"]))
    log(f"SP+ 2024 weekly snapshots: {store.sp_weeks(2024)}")

    # --- predictions ---
    pred_files = sorted(
        glob.glob(str(settings.legacy_season_dir / "Predictions" / "Week *" / "preds_*.csv"))
    )
    n_pred_rows = 0
    for path in pred_files:
        m = PREDS_RE.search(Path(path).name)
        if not m:
            log(f"  SKIP unparseable preds filename: {path}")
            continue
        season, week, day = int(m.group(1)), int(m.group(2)), m.group(3) or ""
        preds = _read_clean(path).dropna(subset=["gameID"])
        store.upsert_predictions(season, week, day, preds)
        n_pred_rows += len(preds)
    log(f"Prediction files migrated: {len(pred_files)} ({n_pred_rows} rows)")

    # --- weekly results ---
    result_files = sorted(glob.glob(str(settings.legacy_season_dir / "Results" / "results_*.csv")))
    n_result_files = 0
    for path in result_files:
        m = RESULTS_RE.search(Path(path).name)
        if not m:
            continue  # season aggregate — derived, regenerated by `analyze`
        season, week = int(m.group(1)), int(m.group(2))
        results = _read_clean(path).dropna(subset=["gameID"])
        if "day" not in results.columns:  # week 1's single dayless run
            results["day"] = ""
        store.upsert_results(season, week, results)
        n_result_files += 1
    log(f"Weekly results files migrated: {n_result_files}")

    store.set_meta("migrated_at", datetime.now(timezone.utc).isoformat())
    return store


# ---------------- validation gate ----------------

def validate_migration(settings: Settings | None = None, log=print, sample_size: int = 5) -> bool:
    """Plan §4 step 6. Returns True when every check passes."""
    settings = settings or get_settings()
    store = Store(settings.db_path)
    ok = True

    def check(name: str, passed: bool, detail: str = ""):
        nonlocal ok
        status = "PASS" if passed else "FAIL"
        log(f"[{status}] {name}" + (f" — {detail}" if detail else ""))
        ok = ok and passed

    fbs_keys = store.team_keys("fbs")
    check("FBS team count == 129", len(fbs_keys) == 129, f"got {len(fbs_keys)}")

    pickles = {
        Path(p).name.split("_model")[0].replace("_", " ")
        for p in glob.glob(str(settings.legacy_team_models / "*2024*.pkl"))
    }
    check(
        "FBS keys == pickled model keys",
        set(fbs_keys) == pickles,
        f"missing={sorted(pickles - set(fbs_keys))[:5]} extra={sorted(set(fbs_keys) - pickles)[:5]}",
    )

    fcs_keys = store.team_keys("fcs")
    check("FCS team count > 100", len(fcs_keys) > 100, f"got {len(fcs_keys)}")

    # Round-trip fidelity on a deterministic sample of FBS frames.
    rng = np.random.default_rng(7)
    sample = sorted(rng.choice(fbs_keys, size=sample_size, replace=False))
    for key in sample:
        src_path = settings.legacy_season_dir / "Week 16" / f"{key.replace(' ', '_')}_2024week16.csv"
        src = pd.read_csv(src_path)
        src = src[[c for c in src.columns if not c.startswith("Unnamed")]]
        src = src[src["School"].notna()].reset_index(drop=True)
        db = store.load_team_frame(key)
        try:
            db_cmp = db[src.columns].copy()
            src_cmp = src.copy()
            for col in BOOL_COLUMNS:
                if col in src_cmp.columns:
                    src_cmp[col] = src_cmp[col].astype(float)
                    db_cmp[col] = db_cmp[col].astype(float)
            pd.testing.assert_frame_equal(db_cmp, src_cmp, check_dtype=False, rtol=1e-9)
            check(f"round-trip {key}", True, f"{len(db)} rows")
        except AssertionError as e:
            check(f"round-trip {key}", False, str(e).splitlines()[0])

    # Year ranges.
    alabama = store.load_team_frame("Alabama")
    check(
        "Alabama year range 2007-2024",
        int(alabama["Year"].min()) == 2007 and int(alabama["Year"].max()) == 2024,
        f"{alabama['Year'].min()}-{alabama['Year'].max()}",
    )

    # Preds/results re-export byte-diff.
    from cfb_model.export import write_preds_csv, write_results_csv

    scratch = settings.output_root / "_migration_validation"
    scratch.mkdir(parents=True, exist_ok=True)

    src_preds_path = settings.legacy_season_dir / "Predictions" / "Week 15" / "preds_2024w15_tue.csv"
    preds = store.load_predictions(2024, 15)
    preds_tue = preds[preds["day"] == "tue"]
    out = write_preds_csv(preds_tue, scratch / "preds_2024w15_tue.csv")
    check(
        "preds_2024w15_tue.csv byte-identical",
        out.read_bytes() == src_preds_path.read_bytes(),
    )

    # Results: content-identical (the legacy files carry a meaningless
    # non-contiguous index from an intermediate frame; new exports use a clean
    # 0..n-1 index — cosmetic deviation, ignored by every reader).
    src_results_path = settings.legacy_season_dir / "Results" / "results_2024w15.csv"
    results = store.load_results(2024, 15).drop(columns=["week"])
    src_results = pd.read_csv(src_results_path)
    src_results = src_results[[c for c in src_results.columns if not c.startswith("Unnamed")]]
    src_order = src_results["gameID"].tolist()
    results = results.set_index("gameID").loc[src_order].reset_index()
    out = write_results_csv(results, scratch / "results_2024w15.csv")
    exported = pd.read_csv(out)
    exported = exported[[c for c in exported.columns if not c.startswith("Unnamed")]]
    try:
        pd.testing.assert_frame_equal(
            exported[src_results.columns], src_results, check_dtype=False, rtol=1e-9
        )
        check("results_2024w15.csv content-identical", True)
    except AssertionError as e:
        check("results_2024w15.csv content-identical", False, str(e).splitlines()[0])

    log("VALIDATION " + ("PASSED" if ok else "FAILED"))
    return ok
